version: "3.9"

services:
  mysql-service:
    image: mysql
    container_name: mysql
    hostname: mysql.local # 设置服务的hostname
    ports:
      - "3306:3306"
    command:
      # MySQL8的密码验证方式默认是 caching_sha2_password，但是很多的连接工具还不支持该方式
      # 就需要手动设置下mysql的密码认证方式为以前的 mysql_native_password 方式
      # --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # root用户的密码
      # MYSQL_USER: user # 创建新用户
      # MYSQL_PASSWORD: user_password # 新用户的密码
    volumes:
      - ./data:/var/lib/mysql:rw
      # - ./conf:/etc/mysql/conf.d
      # - ./logs:/logs
    networks:
      - dev_network

networks:
  dev_network:
    external: true
