version: "3.9"

services:
  redis-service:
    container_name: redis
    image: redis:alpine
    hostname: redis.local # 设置服务的hostname
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data:/data
    networks:
      - dev_network

networks:
  dev_network:
    external: true
